name: qr

services:
  qr-generator:
    image: python:3.13.2-slim
    ports:
      - 7777:7777
    working_dir: /app
    volumes:
      - ./src:/app/src
      - ./requirements.txt:/app/requirements.txt
    command: >
      sh -c "pip install --disable-pip-version-check --root-user-action=ignore --no-cache-dir -r requirements.txt
      && python src/app.py"
    profiles:
      - QR